-- Scripts by Sujata STARTS

USE [OSOL23]
GO
/****** Object:  StoredProcedure [dbo].[DML_SEC_LOGIN_DETAILS]    Script Date: 02-03-2024 14:37:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[DML_SEC_LOGIN_DETAILS]
    @FLAG VARCHAR(10)=NULL,
	@USER_ID int,
	@LOGGED_IN_TIME DATETIME=NULL,
	@LOGGED_OUT_TIME DATETIME=NULL,
	@LOGIN_TYPE varchar(100)=NULL,
	@ENTERED_BY varchar(50)=null
	
	
	
as
BEGIN
IF @FLAG='I'
BEGIN
    INSERT INTO SEC_LOGIN_DETAILS
	(USER_ID,LOGIN_TYPE,ENTERED_BY)
   VALUES (@USER_ID,@LOGIN_TYPE,@ENTERED_BY);

    INSERT INTO SEC_ACTIVE_LOGIN_DETAILS
	(USER_ID,LOGIN_TYPE,ENTERED_BY)
   VALUES (@USER_ID,@LOGIN_TYPE,@ENTERED_BY);
   END
   IF @FLAG='U'
   BEGIN
   UPDATE SEC_LOGIN_DETAILS SET LOGGED_OUT_TIME=CONVERT(datetime, @LOGGED_OUT_TIME,103) WHERE 
   USER_ID=(SELECT TOP 1 USER_ID
FROM SEC_LOGIN_DETAILS
WHERE user_id = @USER_ID
ORDER BY LOGGED_IN_TIME DESC)
   END
   IF @FLAG='D'
   BEGIN
   DELETE FROM SEC_ACTIVE_LOGIN_DETAILS WHERE USER_ID=@USER_ID
   END
END 

--***************************************************************--

GO

/****** Object:  Table [dbo].[SEC_LOGIN_DETAILS]    Script Date: 02-03-2024 15:22:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SEC_LOGIN_DETAILS](
	[LOGIN_MASTER_ID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[USER_ID] [int] NULL,
	[LOGGED_IN_TIME] [datetime] NULL,
	[LOGGED_OUT_TIME] [datetime] NULL,
	[LOGIN_TYPE] [int] NULL,
	[ENTERED_BY] [varchar](50) NOT NULL,
	[ENTERED_ON] [datetime] NULL,
 CONSTRAINT [PK_SEC_LOGIN_DETAILS] PRIMARY KEY CLUSTERED 
(
	[LOGIN_MASTER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SEC_LOGIN_DETAILS] ADD  CONSTRAINT [DF_SEC_LOGIN_DETAILS_LOGGED_IN_TIME]  DEFAULT (getdate()) FOR [LOGGED_IN_TIME]
GO

ALTER TABLE [dbo].[SEC_LOGIN_DETAILS] ADD  CONSTRAINT [DF_SEC_LOGIN_DETAILS_ENTERED_ON]  DEFAULT (getdate()) FOR [ENTERED_ON]
GO

--***********************************************

USE [OSOL23]
GO

/****** Object:  Table [dbo].[SEC_ACTIVE_LOGIN_DETAILS]    Script Date: 02-03-2024 15:23:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SEC_ACTIVE_LOGIN_DETAILS](
	[LOGIN_MASTER_ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NULL,
	[LOGGED_IN_TIME] [datetime] NULL,
	[LOGGED_OUT_TIME] [datetime] NULL,
	[LOGIN_TYPE] [int] NULL,
	[ENTERED_BY] [varchar](50) NULL,
	[ENTERED_ON] [datetime] NULL,
 CONSTRAINT [PK_SEC_ACTIVE_LOGIN_DETAILS] PRIMARY KEY CLUSTERED 
(
	[LOGIN_MASTER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SEC_ACTIVE_LOGIN_DETAILS] ADD  CONSTRAINT [DF_SEC_ACTIVE_LOGIN_DETAILS_LOGGED_IN_TIME]  DEFAULT (getdate()) FOR [LOGGED_IN_TIME]
GO

ALTER TABLE [dbo].[SEC_ACTIVE_LOGIN_DETAILS] ADD  CONSTRAINT [DF_SEC_ACTIVE_LOGIN_DETAILS_ENTERED_ON]  DEFAULT (getdate()) FOR [ENTERED_ON]
GO


-- Scripts by Sujata ENDS




